sudo: false
language: ruby
rvm:
  - 2.3.1
addons:
  postgresql: '9.4'
before_install: gem install bundler -v 1.13.6
before_script:
  - createdb junk_drawer_test -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake
  - bundle exec rake build
